// Re-exports for backward compatibility — hooks moved to src/components
export { useAuth } from '../components/useAuth'
export { useUserProfile } from '../components/useUserProfile'
export { useStudent } from '../components/useStudent'
export { useDegreePrograms } from '../components/useDegreePrograms'
export { useCourses } from '../components/useCourses'
export { useEnrollments } from '../components/useEnrollments'
export { useAnnouncements } from '../components/useAnnouncements'
export { useCalendarEvents } from '../components/useCalendarEvents'
export { useFaculty } from '../components/useFaculty'
export { useStudents } from '../components/useStudents'
export { useRealtimeSubscription } from '../components/useRealtimeSubscription'
